# MiniCRM 模块化监控配置文件
# 此配置文件定义了项目的模块化标准和质量门禁

modularity:
  # 文件大小阈值配置
  thresholds:
    file_size:
      warning: 150 # 文件超过150行发出警告
      error: 200 # 文件超过200行阻止提交
    function_size:
      warning: 30 # 函数超过30行发出警告
      error: 50 # 函数超过50行阻止提交
    class_size:
      warning: 80 # 类超过80行发出警告
      error: 100 # 类超过100行阻止提交
    complexity:
      cyclomatic: 10 # 圈复杂度限制
      cognitive: 15 # 认知复杂度限制
      maintainability: 20 # 维护性指数最低要求

  # 架构层次定义和依赖约束
  architecture:
    layers:
      - name: "ui"
        path: "src/minicrm/ui"
        can_import: ["services", "models", "core", "transfunctions"]
        cannot_import: ["data"]
        description: "用户界面层，负责UI组件和用户交互"

      - name: "services"
        path: "src/minicrm/services"
        can_import: ["data", "models", "core", "transfunctions"]
        cannot_import: ["ui"]
        description: "业务逻辑层，实现核心业务功能"

      - name: "data"
        path: "src/minicrm/data"
        can_import: ["models", "core", "transfunctions"]
        cannot_import: ["ui", "services"]
        description: "数据访问层，负责数据库操作和数据持久化"

      - name: "models"
        path: "src/minicrm/models"
        can_import: ["core", "transfunctions"]
        cannot_import: ["ui", "services", "data"]
        description: "数据模型层，定义业务实体和数据结构"

      - name: "core"
        path: "src/minicrm/core"
        can_import: []
        cannot_import: ["ui", "services", "data", "models"]
        description: "核心工具层，提供基础工具和常量"

      - name: "transfunctions"
        path: "src/transfunctions"
        can_import: []
        cannot_import: ["minicrm"]
        description: "可复用函数库，提供通用功能"

  # transfunctions使用规则
  transfunctions:
    enforce_usage: true # 强制使用transfunctions
    registry_path: "src/transfunctions"
    usage_threshold: 0.8 # 80%的通用功能应使用transfunctions
    duplication_threshold: 3 # 超过3行相似代码就建议使用transfunctions

    # 必须使用transfunctions的功能类别
    mandatory_categories:
      - "data_validation" # 数据验证
      - "data_formatting" # 数据格式化
      - "business_calculations" # 业务计算
      - "crud_operations" # CRUD操作
      - "search_operations" # 搜索操作
      - "report_generation" # 报表生成
      - "document_processing" # 文档处理
      - "import_export" # 导入导出

  # 代码质量规则
  quality:
    # 类型注解要求
    type_annotations:
      required: true # 必须有类型注解
      coverage_threshold: 0.95 # 95%的函数必须有类型注解

    # 文档字符串要求
    docstrings:
      required: true # 必须有文档字符串
      style: "google" # 使用Google风格
      coverage_threshold: 0.90 # 90%的函数必须有文档字符串

    # 测试覆盖率要求
    test_coverage:
      minimum: 0.80 # 最低80%测试覆盖率
      target: 0.90 # 目标90%测试覆盖率

    # 代码重复检查
    duplication:
      max_duplicate_lines: 5 # 最多允许5行重复代码
      similarity_threshold: 0.8 # 相似度超过80%视为重复

  # 文件和目录排除规则
  exclusions:
    files:
      - "tests/*" # 测试文件
      - "scripts/*" # 脚本文件
      - "migrations/*" # 数据库迁移文件
      - "docs/*" # 文档文件
      - "examples/*" # 示例文件
      - "*.md" # Markdown文件
      - "*.txt" # 文本文件
      - "*.json" # JSON配置文件
      - "*.yaml" # YAML配置文件
      - "*.yml" # YAML配置文件

    patterns:
      - "test_*.py" # 测试文件模式
      - "*_test.py" # 测试文件模式
      - "conftest.py" # pytest配置文件
      - "__init__.py" # 包初始化文件（如果只有导入语句）
      - "setup.py" # 安装脚本
      - "manage.py" # 管理脚本

  # 监控和报告配置
  monitoring:
    # 实时监控
    real_time:
      enabled: true # 启用实时监控
      check_on_save: true # 保存时检查
      show_warnings: true # 显示警告
      show_suggestions: true # 显示建议

    # 报告生成
    reporting:
      daily_report: true # 生成日报
      weekly_report: true # 生成周报
      trend_analysis: true # 趋势分析
      export_formats: ["html", "json", "markdown"]

    # 通知设置
    notifications:
      slack_webhook: "" # Slack通知（可选）
      email_recipients: [] # 邮件通知（可选）
      threshold_violations: true # 阈值违规通知

  # Git集成配置
  git_integration:
    pre_commit_hook: true # 启用pre-commit钩子
    pre_push_hook: true # 启用pre-push钩子
    commit_msg_check: false # 提交消息检查（可选）

    # 质量门禁
    quality_gates:
      block_oversized_files: true # 阻止超大文件提交
      block_complex_functions: true # 阻止复杂函数提交
      block_architecture_violations: true # 阻止架构违规提交
      block_missing_tests: false # 阻止缺少测试的提交（可选）

# 项目特定配置
project:
  name: "MiniCRM"
  description: "客户关系管理系统"
  version: "1.0.0"

  # 开发团队配置
  team:
    code_review_required: true # 需要代码审查
    pair_programming: false # 结对编程（可选）

  # 发布配置
  release:
    quality_threshold: 0.85 # 发布质量阈值
    documentation_required: true # 需要文档
    changelog_required: true # 需要更新日志
