# 开发环境专用的更宽松配置
# 使用方法: ruff check --config pyproject-dev.toml

[tool.ruff]
target-version = "py311"
line-length = 88
src = ["src"]

[tool.ruff.lint]
# 开发阶段最小规则集 - 只检查关键问题
select = [
    "E9",   # 语法错误
    "F63",  # 重复参数名
    "F7",   # 语法错误
    "F82",  # 未定义名称
    "F401", # 未使用的导入
    "F841", # 未使用的变量
    "I",    # 导入排序
]

ignore = [
    # 开发阶段忽略所有其他规则
]

[tool.ruff.lint.per-file-ignores]
# 所有文件都使用最宽松的规则
"*" = ["D", "ANN", "S", "T20", "PLR", "C90", "ARG"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
ignore_errors = true
show_error_codes = false
warn_return_any = false
check_untyped_defs = false
disallow_untyped_defs = false
